In [1]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (3.2.1)
Collecting sentence-transformers
  Downloading sentence_transformers-3.3.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.46.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (4.66.6)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (2.5.1+cu121)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.5.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (0.26.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (11.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.20.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)
Downloading sentence_transformers-3.3.1-py3-none-any.whl (268 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 4.9 MB/s eta 0:00:00
Installing collected packages: sentence-transformers
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 3.2.1
    Uninstalling sentence-transformers-3.2.1:
      Successfully uninstalled sentence-transformers-3.2.1
Successfully installed sentence-transformers-3.3.1

In [2]:
import os
import json
from google.colab import drive
import pandas as pd
from datetime import datetime
import ast  #
from sentence_transformers import SentenceTransformer
import pandas as pd
from datetime import datetime, timedelta

In [3]:
model = SentenceTransformer('BAAI/bge-large-zh-v1.5')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/30.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.30G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/394 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/110k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/439k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [4]:
drive.mount('/content/drive')

Mounted at /content/drive

# **Resumes**

In [247]:
file_paths= '/content/drive/My Drive/Matching-Algo-Takafo/Resumes/Machine Learning/json'

In [173]:
file_paths

'/content/drive/My Drive/Matching-Algo-Takafo/Resumes/Machine Learning/json'

In [248]:
import os
import json



file_names = []
resumes = []

# Iterate over all files in the directory
for file_name in os.listdir(file_paths):
    file_path = os.path.join(file_paths, file_name)
    if os.path.isfile(file_path) and file_name.endswith('.json'):
        file_names.append(file_name)
        with open(file_path, 'r') as json_file:
            loaded_resume_dict = json.load(json_file)
            resumes.append(loaded_resume_dict['employment'])

# Sort files numerically
sorted_files_with_resumes = sorted(
    zip(file_names, resumes),
    key=lambda x: int(x[0].split('_')[1].split('.')[0])
)

# Unzip the sorted pairs into separate lists
file_names, resumes = zip(*sorted_files_with_resumes)

# Convert back to lists
file_names = list(file_names)
resumes = list(resumes)

# Print the results
print("Sorted File Names:", file_names)
print("Sorted Resumes:", resumes)

Sorted File Names: ['resume_1.json', 'resume_2.json', 'resume_3.json', 'resume_4.json', 'resume_5.json', 'resume_6.json', 'resume_7.json', 'resume_8.json', 'resume_9.json', 'resume_10.json', 'resume_11.json', 'resume_12.json', 'resume_13.json', 'resume_14.json', 'resume_15.json', 'resume_16.json', 'resume_17.json', 'resume_18.json', 'resume_19.json', 'resume_20.json', 'resume_21.json']

In [249]:
file_names[15]

'resume_16.json'

In [250]:
resumes[15]

[{'job_title': 'Data Scientist & Machine Learning Engineer',
  'employer': 'Cplus Soft',
  'start_date': 'June 2023',
  'end_date': 'Present',
  'job_responsibilities': 'Leverage Python and its associated libraries and frameworks (NumPy, Pandas, Scikit-learn, Keras, etc.) to build machine learning models, including neural networks, for tasks such as classification, regression, clustering, etc. Develop and optimize deep learning models, including convolutional and recurrent neural networks, for computer vision, NLP, and other AI applications. Research and implement state-of-the-art AI techniques, including large language models (LLMs) and generative adversarial networks (GANs). Lead end-to-end machine learning projects, including data collection and cleaning, feature engineering, model development and evaluation, and deployment. Clearly communicate complex data science concepts and model results to stakeholders across organizations. Continuous learning to stay up-to-date on latest advancements in data science, machine learning, and AI technology.',
  'employer_address': {'country': 'Pakistan'}},
 {'job_title': 'Data Analyst',
  'employer': 'HUAWEI Pakistan',
  'start_date': 'November 2021',
  'end_date': 'December 2022',
  'job_responsibilities': 'Created insightful reports, visualizations, and dashboards in Power BI to enable data-driven decision making. Automated delivery processes in Huawei VMS through scripting. Analyzed and processed over 1 million records of educational data to discover relationships and patterns between school budget, performance, enrollment, and demographic variables using Excel and Power Query. Utilized advanced Excel functions and macros to analyze data and highlight key insights. Assisted with ad-hoc data collection and reporting for business requirements. Worked across Microsoft Power Platform: Power Pivot, Power Query, Power Apps and Power BI. Managed data in SharePoint Online lists and document libraries. Partnered with stakeholders and management to prioritize analytics and reporting needs. Interpreted results and produced ongoing reports on key business metrics with actionable insights for the leadership team.',
  'employer_address': {'city': 'Islāmābād', 'country': 'Pakistan'}},
 {'job_title': 'Trainee - Data Scientist',
  'employer': 'Convergent Business Technologies',
  'start_date': 'April 2021',
  'end_date': 'August 2021',
  'job_responsibilities': 'Completed intensive training program focused on data science theory, tools and techniques. Gained proficiency in statistical concepts including probability, distributions, hypothesis testing, regression modeling. Developed core Python programming skills and experience with key data science libraries like Pandas, NumPy and Scikit-Learn. Practiced end-to-end machine learning workflows, including data extraction, cleaning, exploration, feature engineering, model building, evaluation and optimization. Learned basics of SQL and querying databases for analytics. Presented analysis and recommendations to audiences of varying technical skill levels.',
  'employer_address': {}}]

# **Job Description**

In [243]:
file_paths='/content/drive/My Drive/Matching-Algo-Takafo/Job Description/json'

In [244]:
# Iterate over all files in the directory
file_names_jd=[]
job_description=[]
for file_name in os.listdir(file_paths):
    # Build the full file path
    file_path = os.path.join(file_paths, file_name)

    # Check if it's a file and has a .json extension
    if os.path.isfile(file_path) and file_name.endswith('.json'):
        file_names_jd.append(file_name)
        # Open and load the JSON file
        with open(file_path, 'r') as json_file:
            loaded_resume_dict = json.load(json_file)
            job_description.append(loaded_resume_dict['functinal_experince'])
        print(f"Reloaded Dictionary from {file_name}:")
        print(loaded_resume_dict)

Reloaded Dictionary from ml_jd_1.json:
{'job_title': 'Machine Learning Engineer', 'job_type': 'N/A', 'required_experience': '1-3 years', 'education_required': "Bachelor's or Master's degree in Computer Science, Data Science, or a related quantitative field", 'industry': 'Information and Communication Technologies (ICT)', 'job_location': {'city': 'N/A', 'state': 'N/A', 'country': 'N/A'}, 'organization': {'name': 'N/A', 'website': 'N/A'}, 'contact_details': {'contact_name': 'N/A', 'contact_email': 'N/A', 'contact_number': 'N/A'}, 'career_level': 'Individual Contributor', 'functinal_experince': "We are looking for a Machine Learning Engineer with a specialization in Natural Language Processing (NLP) and Machine Learning Operations (MLOps) to join our rapidly growing team. The successful candidate will be a technical leader who is responsible for developing, deploying, and maintaining advanced NLP models in production environments. Your knowledge and insights will be key in driving our organization forward in the era of data-driven decision-making. Design, build, and deploy state-of-the-art NLP models to extract insights and automate processes from text data. Utilize and implement the latest research on transformer-based models (BERT, GPT-4, XLNet, T5, etc.), with expertise in using pre-trained models from Hugging Face. Fine-tune and deploy these models to serve specific business requirements. Develop scalable and efficient data pipelines for annotating, training, and validating machine learning models. Implement MLOps (Machine Learning Operations) practices to automate and improve the ML lifecycle, including data collection, model development, deployment, monitoring, and maintenance. Work closely with other data scientists, engineers, and product managers to integrate machine learning solutions into the company’s products and services. Stay updated with the latest developments in the field of NLP, and apply them in problem-solving. Provide support in setting up, maintaining, and evolving our ML infrastructure. Bachelor's or Master's degree in Computer Science, Data Science, or a related quantitative field. 1-3 years of experience. Deep understanding and hands-on experience in NLP, with a focus on transformer models and contextual embeddings. Proven experience in utilizing, fine-tuning, and deploying pre-trained models from Hugging Face. Proficiency in Python and its data science ecosystem (NumPy, pandas, scikit-learn). Proficiency in distributed computing frameworks such as Dask and Ray. Experience with parallel processing techniques for efficient data processing. Knowledge of data visualization tools and libraries (e.g., Matplotlib, Plotly, Tableau). Experience in using modern machine learning libraries (e.g., TensorFlow, PyTorch). Strong understanding of MLOps concepts, including CI/CD for ML, ML workflows orchestration, model versioning, A/B testing, and monitoring. Familiarity with MLOps tools (Kubeflow, MLflow, Seldon, TFX, etc.). Experience with cloud services (AWS, GCP, Azure) and understanding of distributed systems. Ability to translate complex findings and results into a compelling narrative."}

In [245]:
job_description

["We are looking for a Machine Learning Engineer with a specialization in Natural Language Processing (NLP) and Machine Learning Operations (MLOps) to join our rapidly growing team. The successful candidate will be a technical leader who is responsible for developing, deploying, and maintaining advanced NLP models in production environments. Your knowledge and insights will be key in driving our organization forward in the era of data-driven decision-making. Design, build, and deploy state-of-the-art NLP models to extract insights and automate processes from text data. Utilize and implement the latest research on transformer-based models (BERT, GPT-4, XLNet, T5, etc.), with expertise in using pre-trained models from Hugging Face. Fine-tune and deploy these models to serve specific business requirements. Develop scalable and efficient data pipelines for annotating, training, and validating machine learning models. Implement MLOps (Machine Learning Operations) practices to automate and improve the ML lifecycle, including data collection, model development, deployment, monitoring, and maintenance. Work closely with other data scientists, engineers, and product managers to integrate machine learning solutions into the company’s products and services. Stay updated with the latest developments in the field of NLP, and apply them in problem-solving. Provide support in setting up, maintaining, and evolving our ML infrastructure. Bachelor's or Master's degree in Computer Science, Data Science, or a related quantitative field. 1-3 years of experience. Deep understanding and hands-on experience in NLP, with a focus on transformer models and contextual embeddings. Proven experience in utilizing, fine-tuning, and deploying pre-trained models from Hugging Face. Proficiency in Python and its data science ecosystem (NumPy, pandas, scikit-learn). Proficiency in distributed computing frameworks such as Dask and Ray. Experience with parallel processing techniques for efficient data processing. Knowledge of data visualization tools and libraries (e.g., Matplotlib, Plotly, Tableau). Experience in using modern machine learning libraries (e.g., TensorFlow, PyTorch). Strong understanding of MLOps concepts, including CI/CD for ML, ML workflows orchestration, model versioning, A/B testing, and monitoring. Familiarity with MLOps tools (Kubeflow, MLflow, Seldon, TFX, etc.). Experience with cloud services (AWS, GCP, Azure) and understanding of distributed systems. Ability to translate complex findings and results into a compelling narrative."]

# **Code**

In [ ]:
# Dataframe for Candiates

In [229]:
resumes[4]

[{'job_title': 'Machine Learning Engineer - Ops',
  'employer': 'Liquid Technologies',
  'start_date': 'January 2022',
  'end_date': 'Current',
  'job_responsibilities': 'Researched, designed and deployed next generation of architectures, workﬂows and standards to integrate with key product features across organization. Facilitated integration of machine learning services into technology infrastructure. Gathered customer requirements and developed machine learning product features to address needs. Designed and deployed machine learning models (supervised learning) into product stack in support of product development. Partnered with Computer Vision Engineer to create model training workﬂows for use by end-users. Initiated A/B tests and regression testing to validate model performance using MLOps (Mlﬂow) prior to production for US and Local client.',
  'employer_address': {'city': 'N/A', 'state': 'N/A', 'country': 'N/A'}},
 {'job_title': 'Research And Development Engineer',
  'employer': 'Liquid Technologies',
  'start_date': 'March 2020',
  'end_date': 'December 2021',
  'job_responsibilities': 'Analyzed business requirements into technical requirements for reporting and visualizations, data models and databases. Developed Flask API for Machine Learning use cases. Developed company-wide technical strategy plans for Python-based assets, overseeing development, coding, debugging and deployments. Introduced cloud-based technologies into Python development to expand on-premise deployment options. Dockerization of Machine Learning use cases.',
  'employer_address': {'city': 'N/A', 'state': 'N/A', 'country': 'N/A'}},
 {'job_title': 'Data Science Trainee',
  'employer': 'EPlanet Communications',
  'start_date': 'October 2019',
  'end_date': 'February 2020',
  'job_responsibilities': 'Data Scrapping of 4000 + doctors data from web based sources. Adhoc Queries on SQL (simple and complex queries). Daily Conversion Rate for E-Commerce Product. Peak Hours Analysis. Customer Churn rate (6 months). Extraction of GMV and NMVs Value.',
  'employer_address': {'city': 'N/A', 'state': 'N/A', 'country': 'N/A'}},
 {'job_title': 'Data Engineer Intern',
  'employer': 'Qordata',
  'start_date': 'May 2017',
  'end_date': 'June 2017',
  'job_responsibilities': 'Extraction and Transformation of EFPIA Compliance Health Care Professionals (HCPs) and Health Care Organizations (HCOs) from PDFs. Data Scrapping of HCPs and HCOs from Web Source. Data Cleaning on Excel Sheet as per required SOPs. Adhoc queries on MSSQL for Quality Assurance.',
  'employer_address': {'city': 'N/A', 'state': 'N/A', 'country': 'N/A'}}]

In [196]:
file_names

['resume_1.json',
 'resume_2.json',
 'resume_3.json',
 'resume_4.json',
 'resume_7.json',
 'resume_6.json',
 'resume_5.json',
 'resume_8.json',
 'resume_9.json',
 'resume_12.json',
 'resume_11.json',
 'resume_10.json',
 'resume_14.json',
 'resume_13.json',
 'resume_15.json',
 'resume_16.json',
 'resume_18.json',
 'resume_17.json',
 'resume_20.json',
 'resume_19.json',
 'resume_22.json',
 'resume_21.json']

In [284]:
file_names[0:18]

['resume_1.json',
 'resume_2.json',
 'resume_3.json',
 'resume_4.json',
 'resume_5.json',
 'resume_6.json',
 'resume_7.json',
 'resume_8.json',
 'resume_9.json',
 'resume_10.json',
 'resume_11.json',
 'resume_12.json',
 'resume_13.json',
 'resume_14.json',
 'resume_15.json',
 'resume_16.json',
 'resume_17.json',
 'resume_18.json']

In [283]:
file_names[0:18]

['resume_1.json',
 'resume_2.json',
 'resume_3.json',
 'resume_4.json',
 'resume_5.json',
 'resume_6.json',
 'resume_7.json',
 'resume_8.json',
 'resume_9.json',
 'resume_10.json',
 'resume_11.json',
 'resume_12.json',
 'resume_13.json',
 'resume_14.json',
 'resume_15.json',
 'resume_16.json',
 'resume_17.json',
 'resume_18.json']

In [287]:
import pandas as pd
from datetime import datetime

# Helper function to calculate experience duration in years and months
def calculate_total_experience(start_date: str, end_date: str) -> dict:
    # Check if start_date is just a year (e.g., "2017")
    if len(start_date) == 4 and start_date.isdigit():
        start_date = f"January {start_date}"  # Assume January of that year

    # Try parsing both full and abbreviated month names
    try:
        start = datetime.strptime(start_date, '%B %Y')  # Full month name (e.g., "January 2022")
    except ValueError:
        try:
            start = datetime.strptime(start_date, '%b %Y')  # Abbreviated month name (e.g., "Jan 2022")
        except ValueError:
            start = datetime.strptime(start_date, '%Y')  # Just the year (e.g., "2017")

    # Handle "Present" or "Current" as the end date
    if end_date.lower() in ['present', 'current']:
        end = datetime.now()
    else:
        # Check if end_date is just a year (e.g., "2023")
        if len(end_date) == 4 and end_date.isdigit():
            end_date = f"January {end_date}"  # Assume January of that year

        # Try parsing both full and abbreviated month names for the end date
        try:
            end = datetime.strptime(end_date, '%B %Y')  # Full month name (e.g., "January 2022")
        except ValueError:
            try:
                end = datetime.strptime(end_date, '%b %Y')  # Abbreviated month name (e.g., "Jan 2022")
            except ValueError:
                end = datetime.strptime(end_date, '%Y')  # Just the year (e.g., "2023")

    # Calculate difference in years and months
    delta_years = end.year - start.year
    delta_months = end.month - start.month

    # Adjust for negative months (if the current month is less than the start month)
    if delta_months < 0:
        delta_years -= 1
        delta_months += 12

    return {'year': delta_years, 'month': delta_months}

# Helper function to format start and end dates as "(mm-yy)"
def format_start_end_dates(start, end):
    # Check if start is just a year (e.g., "2017")
    if len(start) == 4 and start.isdigit():
        start = f"January {start}"  # Assume January of that year

    # Try parsing both full and abbreviated month names
    try:
        start_date = datetime.strptime(start, '%B %Y')
    except ValueError:
        try:
            start_date = datetime.strptime(start, '%b %Y')
        except ValueError:
            start_date = datetime.strptime(start, '%Y')

    if end.lower() in ['present', 'current']:  # Handle both 'Present' and 'Current'
        end_date = datetime.now()
    else:
        # Check if end is just a year (e.g., "2023")
        if len(end) == 4 and end.isdigit():
            end = f"January {end}"  # Assume January of that year

        # Try parsing both full and abbreviated month names for the end date
        try:
            end_date = datetime.strptime(end, '%B %Y')
        except ValueError:
            try:
                end_date = datetime.strptime(end, '%b %Y')
            except ValueError:
                end_date = datetime.strptime(end, '%Y')

    # Format the start and end dates as "mm-yy"
    return f"{start_date.month}-{str(start_date.year)[-2:]}", f"{end_date.month}-{str(end_date.year)[-2:]}"



# Process each resume
all_candidates = []

for file_name, employment_history in zip(file_names, resumes):
    job_titles = [job['job_title'] for job in employment_history]
    job_responsibilities = [job['job_responsibilities'] for job in employment_history]

    experience_start_end_dates = []
    experience_durations = []
    total_years = 0
    total_months = 0

    for job in employment_history:
        start_date = job['start_date']
        end_date = job['end_date']

        # Calculate experience for the job
        duration = calculate_total_experience(start_date, end_date)
        total_years += duration['year']
        total_months += duration['month']

        # Format start and end dates
        start_date_formatted, end_date_formatted = format_start_end_dates(start_date, end_date)
        experience_start_end_dates.append(f"({start_date_formatted}, {end_date_formatted})")
        experience_durations.append(f"{duration['year']}.{duration['month']}")

    # Add extra months to total years if applicable
    total_years += total_months // 12
    total_months = total_months % 12

    # Final total experience in "years.months" format
    total_experience = f"{total_years}.{total_months}"

    # Create the candidate info dictionary
    candidate_info = {
        "candidate": file_name,
        "job_title": job_titles,
        "total_experience": total_experience,  # e.g., "4.9"
        "experiences": len(employment_history),
        "experience_start_end_dates": experience_start_end_dates,  # e.g., [(7-22, 11-24), ...]
        "experience_durations": experience_durations,  # e.g., ["2.4", "2.5"]
        "job_responsibilities": job_responsibilities
    }

    all_candidates.append(candidate_info)

# Convert to pandas DataFrame
df = pd.DataFrame(all_candidates)

# Display the DataFrame
print(df)

         candidate                                          job_title  \
0    resume_1.json  [ML Engineer - Freelance, Machine Learning Int...
1    resume_2.json                    [AI Engineer, Research Officer]
2    resume_3.json    [Data Scientist, Data Scientist, Data Engineer]
3    resume_4.json  [Machine learning Engineer, Python Developer, ...
4    resume_5.json  [Machine Learning Engineer - Ops, Research And...
5    resume_6.json  [AI/ML Engineer, Associate Data Scientist, Dat...
6    resume_7.json  [Machine Learning Engineer, Data Engineer Intern]
7    resume_8.json  [Machine learning Engineer, Software Applicati...
8    resume_9.json       [Python Developer, Software Engineer Intern]
9   resume_10.json      [Associate Data Scientist, Teacher Assistant]
10  resume_11.json  [Data Scientist, AI/ML Engineer, Software Engi...
11  resume_12.json  [NLP / Machine Learning Engineer, Machine Lear...
12  resume_13.json  [Artificial Intelligence Engineer, Machine Lea...
13  resume_14.json  [Machine Learning Engineer, Data Scientist, Re...
14  resume_15.json  [Junior AI Engineer, Associate Software Engine...
15  resume_16.json  [Data Scientist & Machine Learning Engineer, D...
16  resume_17.json  [AI Developer, Lab Engineer, Web Developer, Re...
17  resume_18.json  [Machine Learning Engineer, Machine Learning E...
18  resume_19.json  [Machine Learning Engineer, Machine Learning E...
19  resume_20.json  [Machine Learning Engineer, Machine Learning E...
20  resume_21.json  [Associate Software Engineering, Python Develo...

   total_experience  experiences  \
0               1.3            3
1              2.10            2
2               1.5            3
3               4.2            3
4               5.0            4
5               5.2            4
6               3.2            2
7              11.9            5
8               1.4            2
9              2.10            2
10              1.6            3
11              3.3            3
12             2.10            3
13              4.3            5
14              3.1            3
15             2.10            3
16              5.4            4
17              6.3            5
18              6.3            5
19              6.3            5
20              4.9            2

                           experience_start_end_dates  \
0       [(7-23, 11-23), (11-23, 1-24), (2-24, 11-24)]
1                      [(7-22, 11-24), (12-21, 6-22)]
2          [(7-23, 9-23), (6-22, 8-22), (8-22, 9-23)]
3     [(10-22, 11-24), (10-21, 10-22), (9-20, 10-21)]
4   [(1-22, 11-24), (3-20, 12-21), (10-19, 2-20), ...
5   [(7-22, 11-24), (9-20, 6-22), (9-19, 9-20), (7...
6                       [(6-22, 11-24), (9-21, 6-22)]
7   [(2-23, 11-24), (8-20, 1-23), (10-19, 7-20), (...
8                       [(9-23, 11-24), (7-22, 9-22)]
9                      [(7-22, 11-24), (6-22, 12-22)]
10      [(11-23, 11-24), (7-23, 11-23), (7-22, 9-22)]
11      [(9-22, 11-24), (12-21, 8-22), (6-21, 11-21)]
12      [(5-23, 11-24), (11-22, 5-23), (1-22, 11-22)]
13  [(7-23, 11-24), (1-23, 7-23), (9-21, 9-22), (2...
14       [(8-21, 12-21), (2-22, 1-23), (1-23, 11-24)]
15      [(6-23, 11-24), (11-21, 12-22), (4-21, 8-21)]
16  [(8-23, 11-24), (2-21, 7-23), (10-19, 1-21), (...
17  [(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...
18  [(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...
19  [(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...
20                      [(7-22, 11-24), (2-19, 7-21)]

           experience_durations  \
0               [0.4, 0.2, 0.9]
1                    [2.4, 0.6]
2               [0.2, 0.2, 1.1]
3               [2.1, 1.0, 1.1]
4         [2.10, 1.9, 0.4, 0.1]
5          [2.4, 1.9, 1.0, 0.1]
6                    [2.5, 0.9]
7     [1.9, 2.5, 0.9, 0.3, 6.7]
8                    [1.2, 0.2]
9                    [2.4, 0.6]
10              [1.0, 0.4, 0.2]
11              [2.2, 0.8, 0.5]
12             [1.6, 0.6, 0.10]
13    [1.4, 0.6, 1.0, 0.5, 1.0]
14            [0.4, 0.11, 1.10]
15              [1.5, 1.1, 0.4]
16         [1.3, 2.5, 1.3, 0.5]
17  [2.0, 0.11, 0.10, 1.6, 1.0]
18  [2.0, 0.11, 0.10, 1.6, 1.0]
19  [2.0, 0.11, 0.10, 1.6, 1.0]
20                   [2.4, 2.5]

                                 job_responsibilities
0   [I trained various deep learning models (BiLST...
1   [Orchestrated a collaborative effort with the ...
2   [Automated daily Excel reporting tasks using P...
3   [Working on development of infrastructure. Wor...
4   [Researched, designed and deployed next genera...
5   [Design, code, and implement models and algori...
6   [Secured 380+ open-source contributions. Was i...
7   [RealTime Data Analysis, Work on pertained mod...
8   [Implemented asynchronous backend services usi...
9   [Achieved 25% reduction in fraudulent activity...
10  [Developed predictive churn models using ML al...
11  [Built an end-to-end ML/AI project for grammar...
12  [Conceptualize, design, and develop state-of-t...
13  [Developed solutions using Pytextract and Amaz...
14  [Worked on Speech Recognition. Successfully co...
15  [Leverage Python and its associated libraries ...
16  [Developing an app using OpenAI Whisper (ASR) ...
17  [Working on AI related technologies including ...
18  [Working on AI related technologies including ...
19  [Working on AI related technologies including ...
20  [Conducted A/B testing using models trained wi...

In [289]:
df

,candidate,job_title,total_experience,experiences,experience_start_end_dates,experience_durations,job_responsibilities
0,resume_1.json,"[ML Engineer - Freelance, Machine Learning Int...",1.3,3,"[(7-23, 11-23), (11-23, 1-24), (2-24, 11-24)]","[0.4, 0.2, 0.9]",[I trained various deep learning models (BiLST...
1,resume_2.json,"[AI Engineer, Research Officer]",2.10,2,"[(7-22, 11-24), (12-21, 6-22)]","[2.4, 0.6]",[Orchestrated a collaborative effort with the ...
2,resume_3.json,"[Data Scientist, Data Scientist, Data Engineer]",1.5,3,"[(7-23, 9-23), (6-22, 8-22), (8-22, 9-23)]","[0.2, 0.2, 1.1]",[Automated daily Excel reporting tasks using P...
3,resume_4.json,"[Machine learning Engineer, Python Developer, ...",4.2,3,"[(10-22, 11-24), (10-21, 10-22), (9-20, 10-21)]","[2.1, 1.0, 1.1]",[Working on development of infrastructure. Wor...
4,resume_5.json,"[Machine Learning Engineer - Ops, Research And...",5.0,4,"[(1-22, 11-24), (3-20, 12-21), (10-19, 2-20), ...","[2.10, 1.9, 0.4, 0.1]","[Researched, designed and deployed next genera..."
5,resume_6.json,"[AI/ML Engineer, Associate Data Scientist, Dat...",5.2,4,"[(7-22, 11-24), (9-20, 6-22), (9-19, 9-20), (7...","[2.4, 1.9, 1.0, 0.1]","[Design, code, and implement models and algori..."
6,resume_7.json,"[Machine Learning Engineer, Data Engineer Intern]",3.2,2,"[(6-22, 11-24), (9-21, 6-22)]","[2.5, 0.9]",[Secured 380+ open-source contributions. Was i...
7,resume_8.json,"[Machine learning Engineer, Software Applicati...",11.9,5,"[(2-23, 11-24), (8-20, 1-23), (10-19, 7-20), (...","[1.9, 2.5, 0.9, 0.3, 6.7]","[RealTime Data Analysis, Work on pertained mod..."
8,resume_9.json,"[Python Developer, Software Engineer Intern]",1.4,2,"[(9-23, 11-24), (7-22, 9-22)]","[1.2, 0.2]",[Implemented asynchronous backend services usi...
9,resume_10.json,"[Associate Data Scientist, Teacher Assistant]",2.10,2,"[(7-22, 11-24), (6-22, 12-22)]","[2.4, 0.6]",[Achieved 25% reduction in fraudulent activity...
10,resume_11.json,"[Data Scientist, AI/ML Engineer, Software Engi...",1.6,3,"[(11-23, 11-24), (7-23, 11-23), (7-22, 9-22)]","[1.0, 0.4, 0.2]",[Developed predictive churn models using ML al...
11,resume_12.json,"[NLP / Machine Learning Engineer, Machine Lear...",3.3,3,"[(9-22, 11-24), (12-21, 8-22), (6-21, 11-21)]","[2.2, 0.8, 0.5]",[Built an end-to-end ML/AI project for grammar...
12,resume_13.json,"[Artificial Intelligence Engineer, Machine Lea...",2.10,3,"[(5-23, 11-24), (11-22, 5-23), (1-22, 11-22)]","[1.6, 0.6, 0.10]","[Conceptualize, design, and develop state-of-t..."
13,resume_14.json,"[Machine Learning Engineer, Data Scientist, Re...",4.3,5,"[(7-23, 11-24), (1-23, 7-23), (9-21, 9-22), (2...","[1.4, 0.6, 1.0, 0.5, 1.0]",[Developed solutions using Pytextract and Amaz...
14,resume_15.json,"[Junior AI Engineer, Associate Software Engine...",3.1,3,"[(8-21, 12-21), (2-22, 1-23), (1-23, 11-24)]","[0.4, 0.11, 1.10]",[Worked on Speech Recognition. Successfully co...
15,resume_16.json,"[Data Scientist & Machine Learning Engineer, D...",2.10,3,"[(6-23, 11-24), (11-21, 12-22), (4-21, 8-21)]","[1.5, 1.1, 0.4]",[Leverage Python and its associated libraries ...
16,resume_17.json,"[AI Developer, Lab Engineer, Web Developer, Re...",5.4,4,"[(8-23, 11-24), (2-21, 7-23), (10-19, 1-21), (...","[1.3, 2.5, 1.3, 0.5]",[Developing an app using OpenAI Whisper (ASR) ...
17,resume_18.json,"[Machine Learning Engineer, Machine Learning E...",6.3,5,"[(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...","[2.0, 0.11, 0.10, 1.6, 1.0]",[Working on AI related technologies including ...
18,resume_19.json,"[Machine Learning Engineer, Machine Learning E...",6.3,5,"[(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...","[2.0, 0.11, 0.10, 1.6, 1.0]",[Working on AI related technologies including ...
19,resume_20.json,"[Machine Learning Engineer, Machine Learning E...",6.3,5,"[(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...","[2.0, 0.11, 0.10, 1.6, 1.0]",[Working on AI related technologies including ...
20,resume_21.json,"[Associate Software Engineering, Python Develo...",4.9,2,"[(7-22, 11-24), (2-19, 7-21)]","[2.4, 2.5]",[Conducted A/B testing using models trained wi...

# **Embedding and scores**

In [290]:
# Loop through each row in the DataFrame and calculate the similarities
similarities = []
mean_similarities = []

for idx, row in df.iterrows():
    job_responsibilities = row['job_responsibilities']

    # Generate embeddings for the job responsibilities
    candidate_embeddings = model.encode(job_responsibilities, normalize_embeddings=True)

    # Calculate the similarity scores
    similarity_scores = candidate_embeddings @ jd_embedding.T  # Calculate the dot product (similarity)

    # Calculate the mean similarity score for this candidate
    mean_score = similarity_scores.mean()

    # Store the results
    similarities.append(similarity_scores)
    mean_similarities.append(mean_score)

# Add the new columns to the DataFrame
df['similarity_score'] = similarities
df['mean_similarity'] = mean_similarities

print(df)

         candidate                                          job_title  \
0    resume_1.json  [ML Engineer - Freelance, Machine Learning Int...
1    resume_2.json                    [AI Engineer, Research Officer]
2    resume_3.json    [Data Scientist, Data Scientist, Data Engineer]
3    resume_4.json  [Machine learning Engineer, Python Developer, ...
4    resume_5.json  [Machine Learning Engineer - Ops, Research And...
5    resume_6.json  [AI/ML Engineer, Associate Data Scientist, Dat...
6    resume_7.json  [Machine Learning Engineer, Data Engineer Intern]
7    resume_8.json  [Machine learning Engineer, Software Applicati...
8    resume_9.json       [Python Developer, Software Engineer Intern]
9   resume_10.json      [Associate Data Scientist, Teacher Assistant]
10  resume_11.json  [Data Scientist, AI/ML Engineer, Software Engi...
11  resume_12.json  [NLP / Machine Learning Engineer, Machine Lear...
12  resume_13.json  [Artificial Intelligence Engineer, Machine Lea...
13  resume_14.json  [Machine Learning Engineer, Data Scientist, Re...
14  resume_15.json  [Junior AI Engineer, Associate Software Engine...
15  resume_16.json  [Data Scientist & Machine Learning Engineer, D...
16  resume_17.json  [AI Developer, Lab Engineer, Web Developer, Re...
17  resume_18.json  [Machine Learning Engineer, Machine Learning E...
18  resume_19.json  [Machine Learning Engineer, Machine Learning E...
19  resume_20.json  [Machine Learning Engineer, Machine Learning E...
20  resume_21.json  [Associate Software Engineering, Python Develo...

   total_experience  experiences  \
0               1.3            3
1              2.10            2
2               1.5            3
3               4.2            3
4               5.0            4
5               5.2            4
6               3.2            2
7              11.9            5
8               1.4            2
9              2.10            2
10              1.6            3
11              3.3            3
12             2.10            3
13              4.3            5
14              3.1            3
15             2.10            3
16              5.4            4
17              6.3            5
18              6.3            5
19              6.3            5
20              4.9            2

                           experience_start_end_dates  \
0       [(7-23, 11-23), (11-23, 1-24), (2-24, 11-24)]
1                      [(7-22, 11-24), (12-21, 6-22)]
2          [(7-23, 9-23), (6-22, 8-22), (8-22, 9-23)]
3     [(10-22, 11-24), (10-21, 10-22), (9-20, 10-21)]
4   [(1-22, 11-24), (3-20, 12-21), (10-19, 2-20), ...
5   [(7-22, 11-24), (9-20, 6-22), (9-19, 9-20), (7...
6                       [(6-22, 11-24), (9-21, 6-22)]
7   [(2-23, 11-24), (8-20, 1-23), (10-19, 7-20), (...
8                       [(9-23, 11-24), (7-22, 9-22)]
9                      [(7-22, 11-24), (6-22, 12-22)]
10      [(11-23, 11-24), (7-23, 11-23), (7-22, 9-22)]
11      [(9-22, 11-24), (12-21, 8-22), (6-21, 11-21)]
12      [(5-23, 11-24), (11-22, 5-23), (1-22, 11-22)]
13  [(7-23, 11-24), (1-23, 7-23), (9-21, 9-22), (2...
14       [(8-21, 12-21), (2-22, 1-23), (1-23, 11-24)]
15      [(6-23, 11-24), (11-21, 12-22), (4-21, 8-21)]
16  [(8-23, 11-24), (2-21, 7-23), (10-19, 1-21), (...
17  [(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...
18  [(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...
19  [(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...
20                      [(7-22, 11-24), (2-19, 7-21)]

           experience_durations  \
0               [0.4, 0.2, 0.9]
1                    [2.4, 0.6]
2               [0.2, 0.2, 1.1]
3               [2.1, 1.0, 1.1]
4         [2.10, 1.9, 0.4, 0.1]
5          [2.4, 1.9, 1.0, 0.1]
6                    [2.5, 0.9]
7     [1.9, 2.5, 0.9, 0.3, 6.7]
8                    [1.2, 0.2]
9                    [2.4, 0.6]
10              [1.0, 0.4, 0.2]
11              [2.2, 0.8, 0.5]
12             [1.6, 0.6, 0.10]
13    [1.4, 0.6, 1.0, 0.5, 1.0]
14            [0.4, 0.11, 1.10]
15              [1.5, 1.1, 0.4]
16         [1.3, 2.5, 1.3, 0.5]
17  [2.0, 0.11, 0.10, 1.6, 1.0]
18  [2.0, 0.11, 0.10, 1.6, 1.0]
19  [2.0, 0.11, 0.10, 1.6, 1.0]
20                   [2.4, 2.5]

                                 job_responsibilities  \
0   [I trained various deep learning models (BiLST...
1   [Orchestrated a collaborative effort with the ...
2   [Automated daily Excel reporting tasks using P...
3   [Working on development of infrastructure. Wor...
4   [Researched, designed and deployed next genera...
5   [Design, code, and implement models and algori...
6   [Secured 380+ open-source contributions. Was i...
7   [RealTime Data Analysis, Work on pertained mod...
8   [Implemented asynchronous backend services usi...
9   [Achieved 25% reduction in fraudulent activity...
10  [Developed predictive churn models using ML al...
11  [Built an end-to-end ML/AI project for grammar...
12  [Conceptualize, design, and develop state-of-t...
13  [Developed solutions using Pytextract and Amaz...
14  [Worked on Speech Recognition. Successfully co...
15  [Leverage Python and its associated libraries ...
16  [Developing an app using OpenAI Whisper (ASR) ...
17  [Working on AI related technologies including ...
18  [Working on AI related technologies including ...
19  [Working on AI related technologies including ...
20  [Conducted A/B testing using models trained wi...

                                     similarity_score  mean_similarity
0            [[0.67365265], [0.5548587], [0.5739811]]         0.600831
1                        [[0.74998397], [0.71829164]]         0.734138
2            [[0.7343683], [0.57216656], [0.5354332]]         0.613989
3          [[0.66567415], [0.58992374], [0.56782055]]         0.607806
4   [[0.7987827], [0.714859], [0.5174354], [0.5285...         0.639905
5   [[0.7231586], [0.66745716], [0.6586765], [0.69...         0.685663
6                         [[0.7196941], [0.66595376]]         0.692824
7   [[0.72217], [0.6681337], [0.7407088], [0.61837...         0.675785
8                         [[0.80384207], [0.6565919]]         0.730217
9                        [[0.74780816], [0.59743065]]         0.672619
10             [[0.69061], [0.8184172], [0.59053224]]         0.699853
11         [[0.65543735], [0.52659684], [0.49312523]]         0.558387
12           [[0.5511547], [0.6487876], [0.58786154]]         0.595935
13  [[0.67292535], [0.76185155], [0.59343773], [0....         0.695922
14           [[0.69165075], [0.5876335], [0.5545435]]         0.611276
15            [[0.8154483], [0.7003771], [0.7803794]]         0.765402
16  [[0.45292792], [0.64697075], [0.5717533], [0.5...         0.553219
17  [[0.6577121], [0.5548235], [0.403774], [0.4649...         0.527808
18  [[0.6577121], [0.5548235], [0.403774], [0.4649...         0.527808
19  [[0.70777607], [0.54990387], [0.51488197], [0....         0.588204
20                       [[0.75189435], [0.45900035]]         0.605447

In [291]:
df

,candidate,job_title,total_experience,experiences,experience_start_end_dates,experience_durations,job_responsibilities,similarity_score,mean_similarity
0,resume_1.json,"[ML Engineer - Freelance, Machine Learning Int...",1.3,3,"[(7-23, 11-23), (11-23, 1-24), (2-24, 11-24)]","[0.4, 0.2, 0.9]",[I trained various deep learning models (BiLST...,"[[0.67365265], [0.5548587], [0.5739811]]",0.600831
1,resume_2.json,"[AI Engineer, Research Officer]",2.10,2,"[(7-22, 11-24), (12-21, 6-22)]","[2.4, 0.6]",[Orchestrated a collaborative effort with the ...,"[[0.74998397], [0.71829164]]",0.734138
2,resume_3.json,"[Data Scientist, Data Scientist, Data Engineer]",1.5,3,"[(7-23, 9-23), (6-22, 8-22), (8-22, 9-23)]","[0.2, 0.2, 1.1]",[Automated daily Excel reporting tasks using P...,"[[0.7343683], [0.57216656], [0.5354332]]",0.613989
3,resume_4.json,"[Machine learning Engineer, Python Developer, ...",4.2,3,"[(10-22, 11-24), (10-21, 10-22), (9-20, 10-21)]","[2.1, 1.0, 1.1]",[Working on development of infrastructure. Wor...,"[[0.66567415], [0.58992374], [0.56782055]]",0.607806
4,resume_5.json,"[Machine Learning Engineer - Ops, Research And...",5.0,4,"[(1-22, 11-24), (3-20, 12-21), (10-19, 2-20), ...","[2.10, 1.9, 0.4, 0.1]","[Researched, designed and deployed next genera...","[[0.7987827], [0.714859], [0.5174354], [0.5285...",0.639905
5,resume_6.json,"[AI/ML Engineer, Associate Data Scientist, Dat...",5.2,4,"[(7-22, 11-24), (9-20, 6-22), (9-19, 9-20), (7...","[2.4, 1.9, 1.0, 0.1]","[Design, code, and implement models and algori...","[[0.7231586], [0.66745716], [0.6586765], [0.69...",0.685663
6,resume_7.json,"[Machine Learning Engineer, Data Engineer Intern]",3.2,2,"[(6-22, 11-24), (9-21, 6-22)]","[2.5, 0.9]",[Secured 380+ open-source contributions. Was i...,"[[0.7196941], [0.66595376]]",0.692824
7,resume_8.json,"[Machine learning Engineer, Software Applicati...",11.9,5,"[(2-23, 11-24), (8-20, 1-23), (10-19, 7-20), (...","[1.9, 2.5, 0.9, 0.3, 6.7]","[RealTime Data Analysis, Work on pertained mod...","[[0.72217], [0.6681337], [0.7407088], [0.61837...",0.675785
8,resume_9.json,"[Python Developer, Software Engineer Intern]",1.4,2,"[(9-23, 11-24), (7-22, 9-22)]","[1.2, 0.2]",[Implemented asynchronous backend services usi...,"[[0.80384207], [0.6565919]]",0.730217
9,resume_10.json,"[Associate Data Scientist, Teacher Assistant]",2.10,2,"[(7-22, 11-24), (6-22, 12-22)]","[2.4, 0.6]",[Achieved 25% reduction in fraudulent activity...,"[[0.74780816], [0.59743065]]",0.672619
10,resume_11.json,"[Data Scientist, AI/ML Engineer, Software Engi...",1.6,3,"[(11-23, 11-24), (7-23, 11-23), (7-22, 9-22)]","[1.0, 0.4, 0.2]",[Developed predictive churn models using ML al...,"[[0.69061], [0.8184172], [0.59053224]]",0.699853
11,resume_12.json,"[NLP / Machine Learning Engineer, Machine Lear...",3.3,3,"[(9-22, 11-24), (12-21, 8-22), (6-21, 11-21)]","[2.2, 0.8, 0.5]",[Built an end-to-end ML/AI project for grammar...,"[[0.65543735], [0.52659684], [0.49312523]]",0.558387
12,resume_13.json,"[Artificial Intelligence Engineer, Machine Lea...",2.10,3,"[(5-23, 11-24), (11-22, 5-23), (1-22, 11-22)]","[1.6, 0.6, 0.10]","[Conceptualize, design, and develop state-of-t...","[[0.5511547], [0.6487876], [0.58786154]]",0.595935
13,resume_14.json,"[Machine Learning Engineer, Data Scientist, Re...",4.3,5,"[(7-23, 11-24), (1-23, 7-23), (9-21, 9-22), (2...","[1.4, 0.6, 1.0, 0.5, 1.0]",[Developed solutions using Pytextract and Amaz...,"[[0.67292535], [0.76185155], [0.59343773], [0....",0.695922
14,resume_15.json,"[Junior AI Engineer, Associate Software Engine...",3.1,3,"[(8-21, 12-21), (2-22, 1-23), (1-23, 11-24)]","[0.4, 0.11, 1.10]",[Worked on Speech Recognition. Successfully co...,"[[0.69165075], [0.5876335], [0.5545435]]",0.611276
15,resume_16.json,"[Data Scientist & Machine Learning Engineer, D...",2.10,3,"[(6-23, 11-24), (11-21, 12-22), (4-21, 8-21)]","[1.5, 1.1, 0.4]",[Leverage Python and its associated libraries ...,"[[0.8154483], [0.7003771], [0.7803794]]",0.765402
16,resume_17.json,"[AI Developer, Lab Engineer, Web Developer, Re...",5.4,4,"[(8-23, 11-24), (2-21, 7-23), (10-19, 1-21), (...","[1.3, 2.5, 1.3, 0.5]",[Developing an app using OpenAI Whisper (ASR) ...,"[[0.45292792], [0.64697075], [0.5717533], [0.5...",0.553219
17,resume_18.json,"[Machine Learning Engineer, Machine Learning E...",6.3,5,"[(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...","[2.0, 0.11, 0.10, 1.6, 1.0]",[Working on AI related technologies including ...,"[[0.6577121], [0.5548235], [0.403774], [0.4649...",0.527808
18,resume_19.json,"[Machine Learning Engineer, Machine Learning E...",6.3,5,"[(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...","[2.0, 0.11, 0.10, 1.6, 1.0]",[Working on AI related technologies including ...,"[[0.6577121], [0.5548235], [0.403774], [0.4649...",0.527808
19,resume_20.json,"[Machine Learning Engineer, Machine Learning E...",6.3,5,"[(11-22, 11-24), (12-21, 11-22), (1-21, 11-21)...","[2.0, 0.11, 0.10, 1.6, 1.0]",[Working on AI related technologies including ...,"[[0.70777607], [0.54990387], [0.51488197], [0....",0.588204
20,resume_21.json,"[Associate Software Engineering, Python Develo...",4.9,2,"[(7-22, 11-24), (2-19, 7-21)]","[2.4, 2.5]",[Conducted A/B testing using models trained wi...,"[[0.75189435], [0.45900035]]",0.605447

In [298]:
df_selected = df[['candidate', 'job_title','experience_durations','total_experience','experiences','similarity_score', 'mean_similarity']]

# Sort the DataFrame by 'mean_similarity' in descending order
df_sorted = df_selected.sort_values(by='mean_similarity', ascending=False)

In [299]:
df_sorted

,candidate,job_title,experience_durations,total_experience,experiences,similarity_score,mean_similarity
15,resume_16.json,"[Data Scientist & Machine Learning Engineer, D...","[1.5, 1.1, 0.4]",2.10,3,"[[0.8154483], [0.7003771], [0.7803794]]",0.765402
1,resume_2.json,"[AI Engineer, Research Officer]","[2.4, 0.6]",2.10,2,"[[0.74998397], [0.71829164]]",0.734138
8,resume_9.json,"[Python Developer, Software Engineer Intern]","[1.2, 0.2]",1.4,2,"[[0.80384207], [0.6565919]]",0.730217
10,resume_11.json,"[Data Scientist, AI/ML Engineer, Software Engi...","[1.0, 0.4, 0.2]",1.6,3,"[[0.69061], [0.8184172], [0.59053224]]",0.699853
13,resume_14.json,"[Machine Learning Engineer, Data Scientist, Re...","[1.4, 0.6, 1.0, 0.5, 1.0]",4.3,5,"[[0.67292535], [0.76185155], [0.59343773], [0....",0.695922
6,resume_7.json,"[Machine Learning Engineer, Data Engineer Intern]","[2.5, 0.9]",3.2,2,"[[0.7196941], [0.66595376]]",0.692824
5,resume_6.json,"[AI/ML Engineer, Associate Data Scientist, Dat...","[2.4, 1.9, 1.0, 0.1]",5.2,4,"[[0.7231586], [0.66745716], [0.6586765], [0.69...",0.685663
7,resume_8.json,"[Machine learning Engineer, Software Applicati...","[1.9, 2.5, 0.9, 0.3, 6.7]",11.9,5,"[[0.72217], [0.6681337], [0.7407088], [0.61837...",0.675785
9,resume_10.json,"[Associate Data Scientist, Teacher Assistant]","[2.4, 0.6]",2.10,2,"[[0.74780816], [0.59743065]]",0.672619
4,resume_5.json,"[Machine Learning Engineer - Ops, Research And...","[2.10, 1.9, 0.4, 0.1]",5.0,4,"[[0.7987827], [0.714859], [0.5174354], [0.5285...",0.639905
2,resume_3.json,"[Data Scientist, Data Scientist, Data Engineer]","[0.2, 0.2, 1.1]",1.5,3,"[[0.7343683], [0.57216656], [0.5354332]]",0.613989
14,resume_15.json,"[Junior AI Engineer, Associate Software Engine...","[0.4, 0.11, 1.10]",3.1,3,"[[0.69165075], [0.5876335], [0.5545435]]",0.611276
3,resume_4.json,"[Machine learning Engineer, Python Developer, ...","[2.1, 1.0, 1.1]",4.2,3,"[[0.66567415], [0.58992374], [0.56782055]]",0.607806
20,resume_21.json,"[Associate Software Engineering, Python Develo...","[2.4, 2.5]",4.9,2,"[[0.75189435], [0.45900035]]",0.605447
0,resume_1.json,"[ML Engineer - Freelance, Machine Learning Int...","[0.4, 0.2, 0.9]",1.3,3,"[[0.67365265], [0.5548587], [0.5739811]]",0.600831
12,resume_13.json,"[Artificial Intelligence Engineer, Machine Lea...","[1.6, 0.6, 0.10]",2.10,3,"[[0.5511547], [0.6487876], [0.58786154]]",0.595935
19,resume_20.json,"[Machine Learning Engineer, Machine Learning E...","[2.0, 0.11, 0.10, 1.6, 1.0]",6.3,5,"[[0.70777607], [0.54990387], [0.51488197], [0....",0.588204
11,resume_12.json,"[NLP / Machine Learning Engineer, Machine Lear...","[2.2, 0.8, 0.5]",3.3,3,"[[0.65543735], [0.52659684], [0.49312523]]",0.558387
16,resume_17.json,"[AI Developer, Lab Engineer, Web Developer, Re...","[1.3, 2.5, 1.3, 0.5]",5.4,4,"[[0.45292792], [0.64697075], [0.5717533], [0.5...",0.553219
17,resume_18.json,"[Machine Learning Engineer, Machine Learning E...","[2.0, 0.11, 0.10, 1.6, 1.0]",6.3,5,"[[0.6577121], [0.5548235], [0.403774], [0.4649...",0.527808
18,resume_19.json,"[Machine Learning Engineer, Machine Learning E...","[2.0, 0.11, 0.10, 1.6, 1.0]",6.3,5,"[[0.6577121], [0.5548235], [0.403774], [0.4649...",0.527808

# **Extras**

embedding part

In [132]:
job_responsiblites=df["job_responsibilities"].iloc[0]
job_responsiblites

['- Conducted A/B testing using models trained with PyTorch, directly uplifting user.\n- Developed a series of MLflow pipelines that standardized feature engineering processes.\n- Integration FairML principles into all machine learning projects.\n- Transforming data science prototypes and applying appropriate ML algorithms and tools.\n- Implemented a Keras-based anomaly detection system to monitor cloud services.',
 '- Create a match summary In CSV and shows a summary along with a win prediction of an ongoing match.\n- Building various regression, classification and clustering algorithms by using various Sklearn libraries.']

In [137]:
candidate_embeddings = model.encode(job_responsiblites, normalize_embeddings=True)
len(candidate_embeddings)

2

In [138]:
len(candidate_embeddings[0])

1024

In [134]:
job_description

["We are looking for a Machine Learning Engineer with a specialization in Natural Language Processing (NLP) and Machine Learning Operations (MLOps) to join our rapidly growing team. The successful candidate will be a technical leader who is responsible for developing, deploying, and maintaining advanced NLP models in production environments. Your knowledge and insights will be key in driving our organization forward in the era of data-driven decision-making. Design, build, and deploy state-of-the-art NLP models to extract insights and automate processes from text data. Utilize and implement the latest research on transformer-based models (BERT, GPT-4, XLNet, T5, etc.), with expertise in using pre-trained models from Hugging Face. Fine-tune and deploy these models to serve specific business requirements. Develop scalable and efficient data pipelines for annotating, training, and validating machine learning models. Implement MLOps (Machine Learning Operations) practices to automate and improve the ML lifecycle, including data collection, model development, deployment, monitoring, and maintenance. Work closely with other data scientists, engineers, and product managers to integrate machine learning solutions into the company’s products and services. Stay updated with the latest developments in the field of NLP, and apply them in problem-solving. Provide support in setting up, maintaining, and evolving our ML infrastructure. Bachelor's or Master's degree in Computer Science, Data Science, or a related quantitative field. 1-3 years of experience. Deep understanding and hands-on experience in NLP, with a focus on transformer models and contextual embeddings. Proven experience in utilizing, fine-tuning, and deploying pre-trained models from Hugging Face. Proficiency in Python and its data science ecosystem (NumPy, pandas, scikit-learn). Proficiency in distributed computing frameworks such as Dask and Ray. Experience with parallel processing techniques for efficient data processing. Knowledge of data visualization tools and libraries (e.g., Matplotlib, Plotly, Tableau). Experience in using modern machine learning libraries (e.g., TensorFlow, PyTorch). Strong understanding of MLOps concepts, including CI/CD for ML, ML workflows orchestration, model versioning, A/B testing, and monitoring. Familiarity with MLOps tools (Kubeflow, MLflow, Seldon, TFX, etc.). Experience with cloud services (AWS, GCP, Azure) and understanding of distributed systems. Ability to translate complex findings and results into a compelling narrative."]

In [135]:
jd_embedding= model.encode(job_description, normalize_embeddings=True)

In [136]:
jd_embedding

array([[ 0.02851379,  0.00293001, -0.00720338, ..., -0.013761  ,
        -0.00386164, -0.01515182]], dtype=float32)

In [146]:
similarity_scores = candidate_embeddings @ jd_embedding.T

In [147]:
similarity_scores

array([[0.7330241 ],
       [0.46073684]], dtype=float32)

In [149]:
mean_score = similarity_scores.mean()

In [150]:
mean_score

0.5968805

In [144]:
df_1=df

In [27]:
experience_dates=df["experience_durations"].iloc[0]

In [28]:
experience_dates

['2.4', '2.5']

In [30]:
experience_dates=df["experience_durations"]
experience_dates

0    [2.4, 2.5]
Name: experience_durations, dtype: object

In [ ]:
experience_dates=df["job_responsibilities"].iloc[0]

In [ ]:
experience_dates[1]

'- Create a match summary In CSV and shows a summary along with a win prediction of an ongoing match.\n- Building various regression, classification and clustering algorithms by using various Sklearn libraries.'

In [ ]:
experience_dates[0]

'(7-22, 11-24)'

In [ ]:
value=ast.literal_eval(experience_dates[0])

ValueError: malformed node or string on line 1: <ast.BinOp object at 0x7c237ebfb970>

In [ ]:
# Original value
value = '(7-22, 11-24)'

# Strip parentheses and split the values
value_cleaned = value.strip('()')  # Remove '(' and ')'
elements = value_cleaned.split(', ')  # Split into individual components

# Convert into a tuple
tuple_value = tuple(elements)

print(tuple_value)

('7-22', '11-24')

In [ ]:
int(tuple_value[0][0][0])

7

In [ ]:
import ast

# Your string value
value = '(7-22, 11-24)'

# Convert the string to an actual tuple using ast.literal_eval()
tuple_value = ast.literal_eval(value)

print(tuple_value)

ValueError: malformed node or string on line 1: <ast.BinOp object at 0x7c237eaeac20>

In [ ]:
import ast

# Your original value as a string
value = '(7-22, 11-24)'

# Fix the string by adding quotes around the hyphen-separated values
value_fixed = value.replace('-', "'-'")

# Now, safely evaluate the corrected value as a tuple
try:
    # Evaluate it safely
    tuple_value = ast.literal_eval(value_fixed)
    print(tuple_value)
except Exception as e:
    print("Error:", e)

Error: invalid syntax. Perhaps you forgot a comma? (<unknown>, line 1)

In [ ]:
# Helper function to calculate experience duration and format it as "years.months"
def calculate_experience_duration(start, end):
    start_date = datetime.strptime(start, '%B %Y')
    if end.lower() == 'present':
        end_date = datetime.now()
    else:
        end_date = datetime.strptime(end, '%B %Y')
    duration = end_date - start_date
    years = duration.days // 365
    months = (duration.days % 365) // 30
    return round(years + months / 12, 1), f"{years}.{months}"

# Helper function to format start and end dates as "(mm-yy)"
def format_start_end_dates(start, end):
    start_date = datetime.strptime(start, '%B %Y')
    if end.lower() == 'present':
        end_date = datetime.now()
    else:
        end_date = datetime.strptime(end, '%B %Y')
    return f"{start_date.month}-{str(start_date.year)[-2:]}", f"{end_date.month}-{str(end_date.year)[-2:]}"

In [ ]:
# Extras------------------------

In [ ]:
# t2

In [ ]:
# Process the data
job_titles = [job['job_title'] for job in loaded_resume_dict['employment']]
job_responsibilities = [job['job_responsibilities'] for job in loaded_resume_dict['employment']]
experience_start_end_dates = [
    f"{job['start_date']} - {job['end_date']}" for job in loaded_resume_dict['employment']
]
experience_durations = [
    calculate_experience_duration(job['start_date'], job['end_date']) for job in loaded_resume_dict['employment']
]

candidate_info = {
    "candidate": file_name,
    "job_title": job_titles,
    "total_experience": len(loaded_resume_dict['employment']),
    "experience_start_end_dates": experience_start_end_dates,
    "experience_durations": experience_durations,
    "job_responsibilities": job_responsibilities
}

# Convert to pandas DataFrame
df = pd.DataFrame([candidate_info])

# Display the DataFrame
print(df)

       candidate                                          job_title  \
0  resume_1.json  [Associate Software Engineering, Python Develo...

   total_experience                        experience_start_end_dates  \
0                 2  [July 2022 - Present, February 2019 - July 2021]

                     experience_durations  \
0  [2 years, 4 months, 2 years, 5 months]

                                job_responsibilities
0  [- Conducted A/B testing using models trained ...

In [ ]:
df

,candidate,job_title,total_experience,experience_start_end_dates,experience_durations,job_responsibilities
0,resume_1.json,"[Associate Software Engineering, Python Develo...",2,"[July 2022 - Present, February 2019 - July 2021]","[2 years, 4 months, 2 years, 5 months]",[- Conducted A/B testing using models trained ...

In [ ]:
def calculate_experience_duration(start, end):
    start_date = datetime.strptime(start, '%B %Y')
    if end.lower() == 'present':
        end_date = datetime.now()
    else:
        end_date = datetime.strptime(end, '%B %Y')
    duration = end_date - start_date
    years = duration.days // 365
    months = (duration.days % 365) // 30
    return f"{years} years, {months} months"

In [ ]:
file_name = "resume_1.json"

# Process the data
candidate_info = {
    "candidate": file_name,
    "experience": len(loaded_resume_dict['employment']),
    "job_responsibilities": [job['job_responsibilities'] for job in loaded_resume_dict['employment']],

}

# Convert to pandas DataFrame
df = pd.DataFrame([candidate_info])

# Display the DataFrame
print(df)

       candidate  experience  \
0  resume_1.json           2

                                job_responsibilities
0  [- Conducted A/B testing using models trained ...

In [ ]:
df

,candidate,experience,job_responsibilities
0,resume_1.json,2,[- Conducted A/B testing using models trained ...

In [ ]:
a=[(1,2),(4,5)]

In [ ]:
a[0]

(1, 2)

In [ ]:
len(loaded_resume_dict['employment'])

2

In [ ]:
loaded_resume_dict['employment'][0]

{'job_title': 'Associate Software Engineering',
 'employer': 'KavTech Solution PVT',
 'start_date': 'July 2022',
 'end_date': 'Present',
 'job_responsibilities': '- Conducted A/B testing using models trained with PyTorch, directly uplifting user.\n- Developed a series of MLflow pipelines that standardized feature engineering processes.\n- Integration FairML principles into all machine learning projects.\n- Transforming data science prototypes and applying appropriate ML algorithms and tools.\n- Implemented a Keras-based anomaly detection system to monitor cloud services.',
 'employer_address': {'city': '', 'state': '', 'country': ''}}

In [ ]:
2-2019, 2021

In [ ]:
job_responisbilites=[]

In [ ]:
loaded_resume_dict['employment'][0]['job_title']

'Associate Software Engineering'

In [ ]:
loaded_resume_dict['employment'][0]['job_responsibilities']

'- Conducted A/B testing using models trained with PyTorch, directly uplifting user.\n- Developed a series of MLflow pipelines that standardized feature engineering processes.\n- Integration FairML principles into all machine learning projects.\n- Transforming data science prototypes and applying appropriate ML algorithms and tools.\n- Implemented a Keras-based anomaly detection system to monitor cloud services.'

In [ ]:
f_experince=loaded_resume_dict['employment'][1]['job_title']+loaded_resume_dict['employment'][1]['job_responsibilities']

In [ ]:
f_experince

'Python Developer- Create a match summary In CSV and shows a summary along with a win prediction of an ongoing match.\n- Building various regression, classification and clustering algorithms by using various Sklearn libraries.'

In [ ]:
job_responisbilites.append(f_experince)

In [ ]:
job_responisbilites

['Associate Software Engineering- Conducted A/B testing using models trained with PyTorch, directly uplifting user.\n- Developed a series of MLflow pipelines that standardized feature engineering processes.\n- Integration FairML principles into all machine learning projects.\n- Transforming data science prototypes and applying appropriate ML algorithms and tools.\n- Implemented a Keras-based anomaly detection system to monitor cloud services.']